[project]
name = "OpenHRV"
version = "0.2.0"
requires-python = ">= 3.11"
dependencies = [
    "PySide6 == 6.5.2"
]

[project.optional-dependencies]
dev = [
    "black",
    "flake8",
    "mypy"
]
build = [
    "pyinstaller"
]

[tool.black] # https://lyz-code.github.io/blue-book/devops/black/
extend-exclude = "openhrv/resources.py"

[tool.mypy]
check_untyped_defs = true

[project.scripts]
# command line entry points
start_openhrv = "openhrv.app:main"
start_openhrv_test = "openhrv.test_app:main"
