[project]
name = "OpenHRV"
version = "0.2.0"
requires-python = ">=3.11"
dependencies = [
    "PySide6 >= 6.4.0.1",
    "numpy >= 1.23.4"
]

[project.optional-dependencies]
dev = [
    "black",
    "flake8",
]
build = [
    "pyinstaller"
]

[tool.black] # https://lyz-code.github.io/blue-book/devops/black/
extend-exclude = "openhrv/resources.py"
