[project]
name = "OpenHRV"
version = "0.2.0"
requires-python = "== 3.11.*"
dependencies = ["PySide6 == 6.5.2"]

[project.optional-dependencies]
dev = ["snakeviz"]
build = ["pyinstaller"]

[tool.black] # https://lyz-code.github.io/blue-book/devops/black/
extend-exclude = "openhrv/resources.py"

[tool.mypy]
check_untyped_defs = true

[tool.setuptools.packages.find]
where = ["openhrv"]

[project.scripts]
# command line entry points
start_openhrv = "openhrv.app:main"
