name: build with PyInstaller

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:

  build_windows:

    runs-on: windows-latest

    steps:

    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
          python-version: "3.11"

    - name: Install dependencies
      shell: powershell
      run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[build]

    - name: release build
      if: github.event_name == 'release'
      shell: powershell
      run: |
        pyinstaller --onefile --icon=docs/logo.ico --name=OpenHRV openhrv/app.py --windowed

    - name: manual build
      if: github.event_name == 'workflow_dispatch'
      shell: powershell
      run: |
        pyinstaller --onefile --icon=docs/logo.ico --name=OpenHRV openhrv/app.py

    - name: upload exe artifact
      uses: actions/upload-artifact@v3
      with:
        name: OpenHRV_windows
        path: dist/OpenHRV.exe

  upload_windows:    # separate job on Ubuntu since JasonEtco/upload-to-release@master only runs on Linux

    if: github.event_name == 'release'
    needs: build_windows

    runs-on: ubuntu-latest

    steps:

    - name: download exe
      uses: actions/download-artifact@v3
      with:
        name: OpenHRV_windows

    - name: upload exe to release
      uses: JasonEtco/upload-to-release@master
      with:
        args: OpenHRV.exe application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    # token generated implicitly
